export const faqList = [
    { id:1, name: 'What is Faq?', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of" },    
    { id:2, name: 'What are your shipping options?', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of" },    
    { id:3, name: 'How do I create an account?', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of" },    
    { id:4, name: 'Can I modify or cancel my order after placing it?', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of" },    
    { id:5, name: 'How do I place an order?', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of" },    
    { id:6, name: 'How long does it take to process a refund?', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of" },    
    { id:7, name: 'How can I contact customer support?', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of" },    
    { id:8, name: 'What if an item is out of stock?', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of" },    
    { id:9, name: 'Are the products on your site authentic?', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of" },    
    { id:10, name: 'How do I reset my password?', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of" },
    { id:11, name: 'Do I need an account to place an order?', description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of" }
]